spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://27.96.131.56/development?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
#    username: root
#    password: Tambang1230@@
  driver-class-name: org.h2.Driver
  url: jdbc:h2:mem:test
  username: sa
  password:

  ## JPA Setting Info
  jpa:
    hibernate:
      ddl-auto: update  # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
        show_sql: true  # sql 쿼리를 보여줍니다.
        format_sql: true  # sql query formatting
        use_sql_comments: true  # sql 쿼리의 추가정보를 보여줍니다.

logging:
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

server:
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: 1234
    key-alias: tomcat

jwt:
  password: hello_world_tambang # secret key로 사용될 예정